/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author ajid
 */
public class convertSuhu extends javax.swing.JFrame {

    /**
     * Creates new form convertSuhu
     */
    public convertSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonfrom = new javax.swing.ButtonGroup();
        buttonto = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        textInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCelcius = new javax.swing.JRadioButton();
        btnFahrenheit = new javax.swing.JRadioButton();
        btnKelvin = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnConvertCelcius = new javax.swing.JRadioButton();
        btnConvertFahrenheit = new javax.swing.JRadioButton();
        btnConvertKelvin = new javax.swing.JRadioButton();
        btnHasil = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("INPUT");

        jLabel2.setText("FROM");

        buttonfrom.add(btnCelcius);
        btnCelcius.setText("celcius");

        buttonfrom.add(btnFahrenheit);
        btnFahrenheit.setText("fahrenheit");

        buttonfrom.add(btnKelvin);
        btnKelvin.setText("kelvin");

        jLabel3.setText("TO");

        buttonto.add(btnConvertCelcius);
        btnConvertCelcius.setText("celcius");

        buttonto.add(btnConvertFahrenheit);
        btnConvertFahrenheit.setText("fahrenheit");

        buttonto.add(btnConvertKelvin);
        btnConvertKelvin.setText("kelvin");

        btnHasil.setText("HITUNG");
        btnHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasilActionPerformed(evt);
            }
        });

        jLabel4.setText("HASIL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textInput)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFahrenheit)
                            .addComponent(btnCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKelvin))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvertCelcius)
                    .addComponent(btnConvertFahrenheit)
                    .addComponent(btnConvertKelvin))
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(btnHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textHasil)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCelcius)
                    .addComponent(btnConvertCelcius))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFahrenheit)
                    .addComponent(btnConvertFahrenheit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKelvin)
                    .addComponent(btnConvertKelvin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(btnHasil)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasilActionPerformed
        // TODO add your handling code here:
        double input2;
        double hasil;
        
        String input;
        String hasil2;
        
        input= textInput.getText();
        input2=Double.parseDouble(input);
        
        if(btnCelcius.isSelected()){          
            if(btnConvertFahrenheit.isSelected()){
                
             hasil =input2 * 1.8 + 32;
             hasil2=Double.toString(hasil);
             textHasil.setText(hasil2+" Fahrenheit");
              
            }
            
            if(btnConvertKelvin.isSelected()){
             
             hasil =input2 + 273.15;
             hasil2=Double.toString(hasil);
             textHasil.setText(hasil2+" Kelvin");
            }
            
            if(btnConvertCelcius.isSelected()){
               
               textHasil.setText(input2+" Celcius");
            }
        }
        
        
        if(btnFahrenheit.isSelected()){
            if(btnConvertCelcius.isSelected()){
                
             hasil =(input2 - 32) * 0.556;
             hasil2=Double.toString(hasil);
             textHasil.setText(hasil2+" Celcius");
            }
            
            
            if(btnConvertKelvin.isSelected()){
                
             hasil =(input2 - 32) * 0.556 + 273.15;
             hasil2=Double.toString(hasil);
             textHasil.setText(hasil2+" Kelvin");
            }
            
            if(btnConvertFahrenheit.isSelected()){
               
                textHasil.setText(input2+" Fahrenheit");
            }
        }
        
        
        if(btnKelvin.isSelected()){
             if(btnConvertCelcius.isSelected()){
                 
             hasil =input2 - 273.15;
             hasil2=Double.toString(hasil);
             textHasil.setText(hasil2+" Celcius");
             }
             
             if(btnConvertFahrenheit.isSelected()){
                 
             hasil =(input2 - 273.15) * 1.8 + 32;
             hasil2=Double.toString(hasil);
             textHasil.setText(hasil2+" Fahrenheit");
             }
             
             if(btnConvertKelvin.isSelected()){
                 
                 textHasil.setText(input2+" Kelvin");
             }
        }
        
    }//GEN-LAST:event_btnHasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convertSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convertSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convertSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convertSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convertSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCelcius;
    private javax.swing.JRadioButton btnConvertCelcius;
    private javax.swing.JRadioButton btnConvertFahrenheit;
    private javax.swing.JRadioButton btnConvertKelvin;
    private javax.swing.JRadioButton btnFahrenheit;
    private javax.swing.JButton btnHasil;
    private javax.swing.JRadioButton btnKelvin;
    private javax.swing.ButtonGroup buttonfrom;
    private javax.swing.ButtonGroup buttonto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textHasil;
    private javax.swing.JTextField textInput;
    // End of variables declaration//GEN-END:variables
}
